### ISSUE TITLE
Looks like a spambot based on this and https://github.com/diasurgical/devilutionX/pull/137#issuecomment-869243787

### ISSUE THREAD

**Issue by Blacklion55** [semgrep/test-end-to-end-app#6959]
Looks like a spambot based on this and https://github.com/diasurgical/devilutionX/pull/137#issuecomment-869243787

__Originally posted by @glebm in https://github.com/diasurgical/devilutionX/issues/2258#issuecomment-869250116__

**Comment by adamberman** [comment]
I think this was posted in error

**Comment by glebm** [comment]
This issue was posted by the same spambot that's been attacking the devilutionx repo. We've already reported them to GitHub. Not sure what's up with this, as the account does not appear to advertise anything.

**Comment by adamberman** [comment]
Ah thanks @glebm! Appreciate the context.
